### ISSUE TITLE
Docker not using standard env fies

### ISSUE THREAD

**Issue by maciekpaprocki** [Sylius/Sylius-Standard#423]
Although it's common practice for docker to use variables from runtime instead of env files, that will create few issues. 

For example: 
Our .env
```
DATABASE_URL=mysql://root@127.0.0.1/sylius_%kernel.environment%
```

Our docker-compose env:
```
     - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://sylius:nopassword@mysql/sylius?serverVersion=5.7
```

It doesn't seem like an issue, but the fact that we are not using kernel.environment in docker ends up in tests running on this same db as dev. 

Going forward it will surely cause issues as we don't have a single source of truth. 

A potential solution I see would be to annotate .env file with docker variables and remove them from docker-compose ( at least db one ).

**Comment by Ferror** [comment]
@maciekpaprocki There is an issue with `env_file` and `environment` in the docker compose file. First of all when both are defined - the `env_file` stops working. Second, we cant define variables for docker in `.env`, because Docker is not the primary configuration (Sad, but true). Therefore the `environment` are defined in the separation of .env.

Btw. you can always use it in your project:
```yaml
environment:
    DATABASE_URL: "mysql://sylius:nopassword@mysql/sylius_%kernel.environment%"
```
