### ISSUE TITLE
Migration not seen

### ISSUE THREAD

**Issue by malutanpetronel** [Sylius/Sylius-Standard#435]
I've started 2 time https://sylius.com/download/ new project for 1.8. Nice swagger, endpoints work nice with generated JWT.
My issue is that after I add my plugin and copy src/Migrations from plugin to project I try to run the migration with 

bin/console d:m:m 
and I get [OK] Already at the latest version ("Sylius\Bundle\AdminApiBundle\Migrations\Version20170711151342") ... without running my migration from src/Migrations of project

then I also tried to add:
    migrations_paths:
        'Migrations': 'src/Migrations'
        #'SyliusProductDesignConfiguratorPlugin\Migrations': '@SyliusProductDesignConfiguratorPlugin/Migrations'
in config doctrine_migrations.yaml

and run with: bin/console d:m:e App/Migrations/Version20200826223200.php
but I get Migration class "App/Migrations/Version20200826223200.php" was not found? 

Anybody can please help me with this. Many thanks.

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. The problem is correlated with our recent DoctrineMigration adaption. You should check the correctness of namespaces and if it is still needed to copy these files.

I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

**Comment by malutanpetronel** [comment]
thank you. At least I know is something known...
