### ISSUE TITLE
Entity type-hinting error before validation

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius-Standard#449]
Hi guys! I'm facing an issue today about form and i would like to have your point about the subject, I know the submit function triggered before and after the validator listener is called but what if my type-hiting in my setters of my entity is strict?
Imaging i have a an entity like below:

```
<?php

namespace App\Entity;

class Posts {

  /**   
  * @Assert\NotNull(groups={"sylius"})
  **/  
   private $name;

   public function getName(): string
   {
     return $this->name;
   }
   public function setName(string $name)
   {
       $this->name = $name;
   }
}
```

When Symfony map the data to the entity php rise an error like this Expected argument of type string but null given and the code doesn't reach the validation listener.

I tried to add into` ProductType` a `CollectionType` for `ProductVariantType` but when i created a  product and leave empty the pricing, it rise an error before reaching the validation.The error is below

![Screenshot from 2020-12-04 15-18-04](https://user-images.githubusercontent.com/40351002/101158058-8b704980-3644-11eb-8397-71bf9063d959.png)

Sylius version 1.7.6

**Comment by Zales0123** [comment]
Hello @SylvanoTombo!

This is a very important topic and the usual problem that ones can encounter when developing Sylius (but not only) application.

When we use entities in Symfony Forms, we need to be aware of how they work. And that's exactly how you described, the values are nulled before/after the form handles it. What we usually do in Sylius, is making the return types nullable (`?string` etc) even if the property itself should not be null (see, for example, [this method](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Shipping/Model/ShippingMethod.php#L78)). Of course, it's not the perfect solution (such property *really* should not be `null`!), but allows us to skip the problems with Symfony Forms and still we have a validation later (both with Symfony Validation component and on the Doctrine mapping).

There is another option as well. What you can do (and what in fact *should* do) is using Data Transform Objects instead of entities in forms. It resolves these problems totally, allows to keep the entities always valid... but requires some more work. That's why we usually use the first approach, as still a quite good, safe and easier way.

Take a look at the following links regarding DTOs:

https://blog.martinhujer.cz/symfony-forms-with-request-objects/
https://symfonycasts.com/screencast/symfony-forms/form-dto

I hope it answers your questions :) 🖖 🚀

**Comment by SylvanoTombo** [comment]
Thanks for explanation! But I'm wondering why it doesn't rise an error when inside ProductVariantController but in CollectionType ? and the error above is from `Sylius\Component\Core\Model\ProductVariant` `addChannelPricing` function wich has a ChannelPricingInterface type as argument but got null..Do you know a solution for this?

**Comment by Zales0123** [comment]
To be honest... I can't think about any particular solution right now :/ It's hard if I don't see the code, I think you understand that :) Nevertheless, as Sylius issues should be used mainly to post bug reports or propose new features, I would strongly recommend you to discuss it on our Slack - it's the place where you definitely find solutions for your problem 🚀

**Comment by SylvanoTombo** [comment]
@Zales0123 , Thanks for your response!
