### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by gabyrusu** [Sylius/Sylius-Standard#534]
Hi, I can't finish the installation process. I keep getting this error:

![image](https://user-images.githubusercontent.com/3909660/112010395-f0867700-8b2f-11eb-9ad3-2feb60a38e77.png)

I tried the sync-metadata-storage command, but I get the same message. 

- Sylius 1.9
- Windows 10
- PHP 7.4.9
- Composer 2
- Maria DB 10.4.14

I tried installing the same version (1.9) on Ubuntu as well (PHP 7.4, MySQL 8.0, Nginx, Composer 2), but without any success. It says "Updating dependencies..." and that's it. After a few minutes the process is killed without installing the vendors.

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack) (I highly recommend this place!)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

A super quick search suggested issues like this: https://github.com/doctrine/migrations/issues/1003#issuecomment-645810004

I'm closing this, as this issue is related to local env and one of Sylius dependencies.

**Comment by gabyrusu** [comment]
Thanks, @lchrusciel!
The fix for the doctrine issue was very helpful.
The Ubuntu issue persists, but I will use the cannels you suggested.
