### ISSUE TITLE
Running docker-compose pull results in unauthorized errors

### ISSUE THREAD

**Issue by rowanfuchs** [Sylius/Sylius-Standard#566]
docker-compose version 1.29.0, build 07737305
Platform: Windows

The full command `docker-compose pull --ignore-pull-failures || true` fails in windows as the separators are not valid, so I ran `docker-compose pull` but this results into the following error:

```
C:\Projects\Sylius-Standard> docker-compose pull
Pulling mysql   ... done
Pulling php     ... error
Pulling nodejs  ... error
Pulling nginx   ... error
Pulling mailhog ... done

ERROR: for php  unauthorized: access to the requested resource is not authorized

ERROR: for nodejs  unauthorized: access to the requested resource is not authorized

ERROR: for nginx  unauthorized: access to the requested resource is not authorized
ERROR: unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized
```

**Comment by mantans** [comment]
You can refer to these steps that I have indicated here 

#552

**Comment by olimination** [comment]
Hi @rowanfuchs 
as far as I understand the Docker setup this error message is not really an error because docker-compose tries to download the Docker image from `quay.io/sylius/php:latest`. "Quay" is a Docker container management platform provided by Red Hat, see https://quay.io/. So actually what you really want is to build the Docker image in any case by yourself, not pulling it from quay.io.
So just do a docker-compose build directly to build the Docker image, this will then be placed in your local Docker "registry".

**Comment by Ferror** [comment]
It is already fixed
