### ISSUE TITLE
duplicate entry in address table

### ISSUE THREAD

**Issue by rcsofttech85** [Sylius/Sylius-Standard#668]
I have a fresh project installed running docker and on placing a order, I can see duplicate rows in the sylius_address table, I could not fix it and still looking for a solution.

**Comment by vvasiloi** [comment]
That's an expected behavior, don't worry about it.
This is to prevent the customer from changing the addresses after the order was placed.

**Comment by rcsofttech85** [comment]
> That's an expected behavior, don't worry about it. This is to prevent the customer from changing the addresses after the order was placed

doesnt it violate good database designing? i have 3 duplicate rows for a single order which is bit concerned to me..thank you

**Comment by vvasiloi** [comment]
> doesnt it violate good database designing?
Can you be more specific?

**Comment by rcsofttech85** [comment]
151,,Courtney,Wolff,,499 Jalon Turnpike Suite 368,,Rogahnburgh,40472-2766,2022-02-02 13:14:51,2022-02-02 13:14:51,US,,
150,,Courtney,Wolff,,499 Jalon Turnpike Suite 368,,Rogahnburgh,40472-2766,2022-02-02 13:14:51,2022-02-02 13:14:51,US,,
149,30,Courtney,Wolff,,499 Jalon Turnpike Suite 368,,Rogahnburgh,40472-2766,2022-02-02 13:14:51,2022-02-02 13:14:51,US


This is the sample data on fixture load, i guess the first two records stored is unnecessary, if you look at amazon checkout they  only  allow shipping address to be modified, there is no such thing called billing address even if it exists, It should be moved to profile section. i belive this is how it should be done, avoid storing billing address  on each order placed and record should be persisted once the order is complete by doing this database is much cleaner and easy to maintain.

**Comment by vvasiloi** [comment]
That's because Amazon does not allow guest checkout. Sylius does, that's why there's a billing address on order and not on the user profile.

**Comment by rcsofttech85** [comment]
I understand that it allows guest checkout, could you try to place an order with logged user and find out the number of rows in the table? in my case it does not make any difference , I still have 3 rows , then how does it differ from guest checkout?  closing the topic thank you.

**Comment by vvasiloi** [comment]
This is by design. The `sylius_address` holds the order addresses (billing and shipping) and the addresses from the user's address book.
So, from those 3 entries, one is the billing address, a second one is the shipping address and a third one is from address book.
When placing an order with an authenticated user, Sylius automatically adds the unique addresses from the order to the user's address book.
Similarly, when an authenticated user chooses an address from the address book, it's not referenced, but cloned when attached to the order.
If it would be referenced, then any changes the user makes to the address in the address book will be reflected on the placed orders.

Here's an example of how this can go bad.
Let's say the store offers free shipping in France, but charges for shipping outside France, let's say it's charges 5 EUR to ship to Belgium.
The customer can use an address in France during the checkout and not pay for the shipping, but after the order is placed the users goes to the address book and changes the address to one in Belgium.
The store just lost 5 EUR.
This is a simple example, but the consequences of not making the order addresses immutable from the user's perspective can be far more serious.

**Comment by rcsofttech85** [comment]
Hi,
how would i verify if the order has same billing and shipping address on order complete? i was looking for something like order->isBillingAndShippingAddressSame() returns true or false, if that is not the case do i need to get addresses and compare it manually ?? help appreciated !!
